#!/bin/bash

# 获取当前时间并格式化
VERSION=$(date +'%y.%m%d.%H%M%S')

# 更新Java文件中的VERSION值
sed -i "s/VERSION = \".*\"/VERSION = \"$VERSION\"/" datashadow-datasource-sdk/src/main/java/com/tangyujun/datashadow/core/Commit.java

# 将修改后的文件添加到暂存区
git add datashadow-datasource-sdk/src/main/java/com/tangyujun/datashadow/core/Commit.java 